### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by vvidov** [PacktPublishing/raspberry-pi-computer-vision-programming#1]
hello, where are file form dataset folder?

**Comment by gaurav-packt** [comment]
Hello @vvidov, the files in the dataset directory can be found online and the author has included the URLs in the relevant chapter. You can refer to chapter 3 and 4 for the URLs to the dataset. These are standard image datasets.

Closing the issue. Please feel free to reach out for any queries.

**Comment by vvidov** [comment]
Hello, has Somebody tested that? Or IT IS how it was:)

**Comment by gaurav-packt** [comment]
We do perform validation and verification of the code from our end.
